# Calculating Fibonacci sequence using repeated matrix multiplication

0, 1, 1, 2, 3, 5, 8, 13, 21, 34

In [1]:
import numpy as np

In [2]:
F = np.array([[0,1],[1,1]])
F

array([[0, 1],
       [1, 1]])

In [3]:
for i in range(10):
    F_n = np.eye(2)
    for j in range(i):
        F_n = np.matmul(F_n, F)
    print(F_n)
    print()

[[1. 0.]
 [0. 1.]]

[[0. 1.]
 [1. 1.]]

[[1. 1.]
 [1. 2.]]

[[1. 2.]
 [2. 3.]]

[[2. 3.]
 [3. 5.]]

[[3. 5.]
 [5. 8.]]

[[ 5.  8.]
 [ 8. 13.]]

[[ 8. 13.]
 [13. 21.]]

[[13. 21.]
 [21. 34.]]

[[21. 34.]
 [34. 55.]]

