# Eigendecomposition of diagonalizable matrix
For a **$n \times n$** diagonalizable matrix **$A$** , there exist **$n$** independent eigenvectors **$q_i, i = 1, 2, 3, ..., n$** and there corresponding eigenvalues **v_i, i = 1, 2, 3, ..., n**. Then the diagonalizable matrix **$A$** can be decomposde as:

$$A = Q\Lambda Q^{-1}$$

Where,
$$Q = [p_1, p_2, p_3, ..., p_n]$$

$$\Lambda = diag([v_1, v_2, v_3, ..., v_n])$$

Here is a small demostration of eigendecomposition.

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
A

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 1,  0, -1]])

In [3]:
v, Q = LA.eig(A)
print(v)
print()
print(Q)

[ 4.31662479e+00 -2.31662479e+00  1.47314580e-16]

[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


You should notice that the Q here is the eigenvector matrix **$Q$** mentioned above.

In [4]:
print('Ap_1 = ')
print(np.matmul(A, Q[:, 0]))
print('v_1p_1 = ')
print(v[0] * Q[0, :])

Ap_1 = 
[2.52212416 3.47089307 0.47438446]
v_1p_1 = 
[2.52212416 3.1768539  1.76225469]


And the matrix **Lambda** here is the diagonal eigenvalue matrix **$\Lambda$** mentioned above.

In [5]:
Lambda = np.diag(v)
Lambda

array([[ 4.31662479e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -2.31662479e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.47314580e-16]])

In [6]:
A_ = np.matmul(np.matmul(Q, Lambda), np.linalg.inv(Q))
A_

array([[ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
       [ 3.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.03603991e-16, -1.00000000e+00]])

You can see, the decomposed **$Q \Lambda Q^{-1}$** is exactly the same as the original matrix **$A$**.